version: "3"

services:
  frontend:
    build:
      context: ./my-next-app
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./my-next-app:/next
    container_name: next
    env_file:
      - ./my-next-app/.env.local
  nest:
    build:
      context: ./my-nest-app
      dockerfile: dockerfile
    ports:
      - 5000:5000
    container_name: nest


